### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by mikedizon** [calvinfroedge/react-redux-auth0#3]
I have the environment variables loaded using dotenv. I can verify that they're loading. Are there any steps missing from the README?

auth0 mount error Error: `domain` required as second parameter.(…)

**Comment by calvinfroedge** [comment]
@mikedizon Hey Mike, how are you compiling? If you're using webpack, you should be able to add the following to your webpack config: 

``` js
const env = process.env.NODE_ENV;
const AUTH0_CLIENTID = process.env.AUTH0_CLIENTID;
const AUTH0_DOMAIN = process.env.AUTH0_DOMAIN;
```

``` js
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(env),
      'process.env.AUTH0_CLIENTID': JSON.stringify(AUTH0_CLIENTID),
      'process.env.AUTH0_DOMAIN': JSON.stringify(AUTH0_DOMAIN)
    })
  ]
```

That's in the dev server code for the library. You should be able to debug this by checking the env variables you have available in your webpack config when it runs.

**Comment by mikedizon** [comment]
Ah I figured it out. Apologies, I should have you updated the ticket. Nice
work!

On Thursday, May 12, 2016, Calvin Froedge notifications@github.com wrote:

> @mikedizon https://github.com/mikedizon Hey Mike, how are you
> compiling? If you're using webpack, you should be able to add the following
> to your webpack config:
> 
> const env = process.env.NODE_ENV;const AUTH0_CLIENTID = process.env.AUTH0_CLIENTID;const AUTH0_DOMAIN = process.env.AUTH0_DOMAIN;
> 
>   plugins: [
>     new webpack.optimize.OccurenceOrderPlugin(),
>     new webpack.DefinePlugin({
>       'process.env.NODE_ENV': JSON.stringify(env),
>       'process.env.AUTH0_CLIENTID': JSON.stringify(AUTH0_CLIENTID),
>       'process.env.AUTH0_DOMAIN': JSON.stringify(AUTH0_DOMAIN)
>     })
>   ]
> 
> That's in the dev server code for the library. I'll add it to the
> documentation.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/calvinfroedge/react-redux-auth0/issues/3#issuecomment-218866124

## 

Sent from Gmail Mobile
