### ISSUE TITLE
Unable to import AuthMiddleware

### ISSUE THREAD

**Issue by abhikannan** [calvinfroedge/react-redux-auth0#6]
import { AuthMiddleware } from 'react-redux-auth0'
let middlewares = applyMiddleware(routerMiddleware, thunk, AuthMiddleware)

I am getting the following error on the browser
bundle.js:30963 Uncaught TypeError: middleware is not a function

**Comment by calvinfroedge** [comment]
Sorry, there was a typo in the readme. Here is a complete example.

```
import { AuthMiddleware } from 'react-redux-auth0'

let middlewares = applyMiddleware(
    AuthMiddlewares.TokenMiddleware(),
    AuthMiddlewares.AuthMiddlewareHook([
      {
        type: auth.signin,
        func: (payload, state, dispatch)=>{
          console.log("I was called on signin!", payload, state, dispatch);
        }
      }
    ])
)
```
